name: jaguar_dart_server
description: A simple command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  path:
    ^1.8.0
    # lints: ^1.0.0
  jaguar: "3.1.1"
  mysql1: "0.19.2"
  crypto: "3.0.1"
  convert: "3.0.1"
  intl: 0.17.0

# dev_dependencies:
